name: Test, build & deploy to Netlify

on:
  push:
    branches: [ master ]
  repository_dispatch: # will enable starting the workflow using HTTP POST externally
    branches: [ master ]
  workflow_dispatch: # will enable starting the workflow from UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: Setup Node.js env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      - run: yarn
      - name: Test
        run: yarn lint
      
      - name: Build
        run: yarn build
        env:
          GRAPHCMS_ENDPOINT: ${{ secrets.GRAPHCMS_ENDPOINT }}

      - name: Netlify action
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: './public'
          production-branch: master
          deploy-message: ${{ github.event.head_commit.message }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
 
