# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest # runner that the job will run on
    steps:
      - name: Checkout code # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: Setup Node.js env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      # Run a set of commands using the runners shell 
      - run: yarn 
      - run: yarn lint
 
